CREATE DATABASE IF NOT EXISTS PiggyBack;

USE PiggyBack;

CREATE TABLE IF NOT EXISTS Users (
	id INT(11) PRIMARY KEY AUTO_INCREMENT,
	username VARCHAR(64) NOT NULL UNIQUE,
	firstname VARCHAR(64) NOT NULL,
	lastname VARCHAR(64) NOT NULL,
	password VARCHAR(100) NOT NULL,
	phone VARCHAR(32) NOT NULL,
	skipSMS TINYINT(1) DEFAULT 1
);
